import type fr from '../fr/guidesExport'
import type { Structure } from '../../types'

/** Italien — espace « guidesExport » (backlog § BL.2), traduit depuis le français. */
const guidesExport: Structure<typeof fr> = {
  trade_republic: { sousTitre: "Storico delle transazioni", intro: "Un registro completo delle transazioni (acquisti, vendite, dividendi), dal quale l’applicazione ricostruisce tutto il portafoglio. Da non confondere con un semplice estratto delle posizioni.", etape1: "Scarica lo storico completo del tuo conto in formato CSV.", etape2: "Verifica che copra TUTTO il periodo dall’apertura del conto: la ricostruzione riparte da zero a ogni importazione.", etape3: "Trascina il file su questo riquadro.", colonnes: "Il file deve avere le colonne datetime, date, category, type, asset_class, symbol, shares, price, amount e fee. Il formato è riconosciuto automaticamente: nessuna associazione di colonne da fare." },
  ledger: { sousTitre: "Wallet cripto", intro: "Un’esportazione delle operazioni del tuo wallet hardware. Ogni ricezione è trattata come un acquisto al prezzo del giorno di ricezione.", etape1: "Apri Ledger Live sul tuo computer.", etape2: "Richiedi l’esportazione delle operazioni di tutti i tuoi conti in formato CSV.", etape3: "Trascina il file su questo riquadro, poi deseleziona i token indesiderati (spam, polvere) prima di confermare.", colonnes: "Il file deve avere le colonne Operation Date, Status, Currency Ticker, Operation Type, Operation Amount e Countervalue at Operation Date." },
  bricks: { sousTitre: "Crowdfunding immobiliare", intro: "Un’esportazione delle tue transazioni: acquisti di brick, rimborsi e redditi percepiti. I redditi alimentano il calendario dei dividendi.", etape1: "Accedi alla tua area Bricks.co.", etape2: "Richiedi l’esportazione dello storico delle tue transazioni (CSV o Excel).", etape3: "Trascina il file su questo riquadro.", colonnes: "Il file deve avere le colonne id, date, type, statut, propriété, type de contrat, montant (€) e prix de la brick (€). Sono importate solo le righe con stato «Validée»." },
  releve: { nom: "Estratto delle posizioni", sousTitre: "Qualsiasi altro broker", intro: "Per un broker il cui formato non è riconosciuto automaticamente (Boursorama, Degiro, Interactive Brokers...). Associ tu stesso le colonne del file ai campi previsti.", etape1: "Esporta il tuo portafoglio dal tuo broker in formato CSV o Excel.", etape2: "Trascina il file su questo riquadro.", etape3: "Associa almeno una colonna Ticker e una colonna Quantità; prezzo di carico, nome, conto e valuta restano facoltativi.", colonnes: "Nessun nome di colonna imposto: il file è letto così com’è e l’associazione si fa al passo successivo. Il separatore (virgola, punto e virgola, tabulazione) è rilevato automaticamente." },
  bancaire: { nom: "Movimenti bancari", sousTitre: "Per la schermata Budget", intro: "L’estratto del tuo conto corrente, che alimenta la schermata Budget, indipendente dal portafoglio di borsa.", etape1: "Dalla tua area bancaria online, esporta i movimenti del conto in formato OFX, QIF o CSV.", etape2: "Trascina il file su questo riquadro.", etape3: "Un OFX o un QIF è importato direttamente. Un CSV richiede di associare almeno una colonna Data, una colonna Descrizione e la o le colonne dell’importo." },
}

export default guidesExport
