import type fr from '../fr/guidesExport'
import type { Structure } from '../../types'

/** Espagnol — espace « guidesExport » (backlog § BL.2), traduit depuis le français. */
const guidesExport: Structure<typeof fr> = {
  trade_republic: { sousTitre: "Historial de transacciones", intro: "Un libro de transacciones completo (compras, ventas, dividendos), a partir del cual la aplicación reconstruye toda la cartera. No confundir con un simple extracto de posiciones.", etape1: "Descarga el historial completo de tu cuenta en formato CSV.", etape2: "Comprueba que cubre TODO el periodo desde la apertura de la cuenta: la reconstrucción empieza de cero en cada importación.", etape3: "Suelta el archivo en esta ficha.", colonnes: "El archivo debe tener las columnas datetime, date, category, type, asset_class, symbol, shares, price, amount y fee. El formato se reconoce automáticamente: no hay que asociar columnas." },
  ledger: { sousTitre: "Wallet cripto", intro: "Una exportación de las operaciones de tu wallet físico. Cada recepción se trata como una compra al precio del día de recepción.", etape1: "Abre Ledger Live en tu ordenador.", etape2: "Solicita la exportación de las operaciones de todas tus cuentas en formato CSV.", etape3: "Suelta el archivo en esta ficha y desmarca los tokens no deseados (spam, polvo) antes de confirmar.", colonnes: "El archivo debe tener las columnas Operation Date, Status, Currency Ticker, Operation Type, Operation Amount y Countervalue at Operation Date." },
  bricks: { sousTitre: "Crowdfunding inmobiliario", intro: "Una exportación de tus transacciones: compras de ladrillos, reembolsos e ingresos percibidos. Los ingresos alimentan el calendario de dividendos.", etape1: "Conéctate a tu espacio Bricks.co.", etape2: "Solicita la exportación del historial de tus transacciones (CSV o Excel).", etape3: "Suelta el archivo en esta ficha.", colonnes: "El archivo debe tener las columnas id, date, type, statut, propriété, type de contrat, montant (€) y prix de la brick (€). Solo se importan las líneas con estado «Validée»." },
  releve: { nom: "Extracto de posiciones", sousTitre: "Cualquier otro bróker", intro: "Para un bróker cuyo formato no se reconoce automáticamente (Boursorama, Degiro, Interactive Brokers...). Tú mismo asocias las columnas del archivo a los campos esperados.", etape1: "Exporta tu cartera desde tu bróker en formato CSV o Excel.", etape2: "Suelta el archivo en esta ficha.", etape3: "Asocia como mínimo una columna Ticker y una columna Cantidad; el precio de coste, el nombre, la cuenta y la divisa son opcionales.", colonnes: "Ningún nombre de columna impuesto: el archivo se lee tal cual y la asociación se hace en el siguiente paso. El separador (coma, punto y coma, tabulación) se detecta automáticamente." },
  bancaire: { nom: "Movimientos bancarios", sousTitre: "Para la pantalla Presupuesto", intro: "El extracto de tu cuenta corriente, que alimenta la pantalla Presupuesto, independiente de la cartera bursátil.", etape1: "Desde tu banca online, exporta los movimientos de la cuenta en formato OFX, QIF o CSV.", etape2: "Suelta el archivo en esta ficha.", etape3: "Un OFX o QIF se importa directamente. Un CSV requiere asociar al menos una columna Fecha, una columna Concepto y la(s) columna(s) de importe." },
}

export default guidesExport
