import type fr from '../fr/guidesExport'
import type { Structure } from '../../types'

/** Allemand — espace « guidesExport » (backlog § BL.2), traduit depuis le français. */
const guidesExport: Structure<typeof fr> = {
  trade_republic: { sousTitre: "Transaktionshistorie", intro: "Ein vollständiges Transaktionsjournal (Käufe, Verkäufe, Dividenden), aus dem die App das gesamte Portfolio rekonstruiert. Nicht zu verwechseln mit einer einfachen Positionsübersicht.", etape1: "Lade die vollständige Historie deines Kontos im CSV-Format herunter.", etape2: "Prüfe, dass sie den GESAMTEN Zeitraum seit Kontoeröffnung abdeckt: Die Rekonstruktion beginnt bei jedem Import von vorn.", etape3: "Lege die Datei auf dieser Kachel ab.", colonnes: "Die Datei muss die Spalten datetime, date, category, type, asset_class, symbol, shares, price, amount und fee enthalten. Das Format wird automatisch erkannt — keine Spaltenzuordnung nötig." },
  ledger: { sousTitre: "Krypto-Wallet", intro: "Ein Export der Vorgänge deiner Hardware-Wallet. Jeder Eingang wird als Kauf zum Kurs des Eingangstags behandelt.", etape1: "Öffne Ledger Live auf deinem Computer.", etape2: "Fordere den Export der Vorgänge aller deiner Konten im CSV-Format an.", etape3: "Lege die Datei auf dieser Kachel ab und entferne vor dem Bestätigen unerwünschte Token (Spam, Staub).", colonnes: "Die Datei muss die Spalten Operation Date, Status, Currency Ticker, Operation Type, Operation Amount und Countervalue at Operation Date enthalten." },
  bricks: { sousTitre: "Immobilien-Crowdfunding", intro: "Ein Export deiner Transaktionen: Brick-Käufe, Rückzahlungen und erhaltene Erträge. Die Erträge fließen in den Dividendenkalender.", etape1: "Melde dich in deinem Bricks.co-Bereich an.", etape2: "Fordere den Export deiner Transaktionshistorie an (CSV oder Excel).", etape3: "Lege die Datei auf dieser Kachel ab.", colonnes: "Die Datei muss die Spalten id, date, type, statut, propriété, type de contrat, montant (€) und prix de la brick (€) enthalten. Nur Zeilen mit Status „Validée“ werden importiert." },
  releve: { nom: "Positionsübersicht", sousTitre: "Jeder andere Broker", intro: "Für einen Broker, dessen Format nicht automatisch erkannt wird (Boursorama, Degiro, Interactive Brokers...). Du ordnest die Spalten der Datei selbst den erwarteten Feldern zu.", etape1: "Exportiere dein Portfolio bei deinem Broker im CSV- oder Excel-Format.", etape2: "Lege die Datei auf dieser Kachel ab.", etape3: "Ordne mindestens eine Spalte Ticker und eine Spalte Menge zu; Einstandspreis, Name, Konto und Währung bleiben optional.", colonnes: "Keine Spaltennamen vorgeschrieben: Die Datei wird unverändert gelesen, die Zuordnung erfolgt im nächsten Schritt. Das Trennzeichen (Komma, Semikolon, Tabulator) wird automatisch erkannt." },
  bancaire: { nom: "Kontobewegungen", sousTitre: "Für den Bildschirm Budget", intro: "Der Auszug deines Girokontos, der den Bildschirm Budget speist — unabhängig vom Wertpapierportfolio.", etape1: "Exportiere im Onlinebanking die Kontobewegungen im Format OFX, QIF oder CSV.", etape2: "Lege die Datei auf dieser Kachel ab.", etape3: "Eine OFX- oder QIF-Datei wird direkt importiert. Bei einer CSV-Datei müssen mindestens eine Spalte Datum, eine Spalte Buchungstext und die Betragsspalte(n) zugeordnet werden." },
}

export default guidesExport
