"""ajoute cours_historique, cours_serie et echec_structurel

Backlog § AB (Lot 13) — donne un modèle relationnel aux séries de cours, jusqu'ici
sans table : re-téléchargées à chaque calcul à froid (23 s mesurées, dont 98 % de
réseau) ou noyées dans des blobs JSON d'agrégats dérivés expirant toutes les 24 h.

Purement ADDITIVE : deux tables neuves et une colonne à valeur par défaut. Aucune
donnée existante n'est lue, modifiée ni déplacée — les tables se remplissent d'
elles-mêmes au premier calcul qui en a besoin, et une base non migrée continue de
fonctionner à l'identique (repli réseau) tant qu'elles sont vides.

Revision ID: db4ea30e560a
Revises: 95d5e30459ea
Create Date: 2026-09-14 01:17:10.578044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4ea30e560a'
down_revision: Union[str, Sequence[str], None] = '95d5e30459ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cours_historique',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('cloture', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    op.create_table('cours_serie',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('devise', sa.String(), nullable=True),
    sa.Column('premiere_date', sa.String(), nullable=True),
    sa.Column('derniere_date', sa.String(), nullable=True),
    sa.Column('sans_donnees', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('derniere_maj', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    with op.batch_alter_table('ticker_resolution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('echec_structurel', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticker_resolution', schema=None) as batch_op:
        batch_op.drop_column('echec_structurel')

    op.drop_table('cours_serie')
    op.drop_table('cours_historique')
    # ### end Alembic commands ###
