import type fr from '../fr/guidesExport'
import type { Structure } from '../../types'

/** Anglais — espace « guidesExport » (backlog § BL.2), traduit depuis le français. */
const guidesExport: Structure<typeof fr> = {
  trade_republic: { sousTitre: "Transaction history", intro: "A complete transaction ledger (purchases, sales, dividends), from which the app rebuilds the whole portfolio. Not to be confused with a simple positions statement.", etape1: "Download your account’s full history in CSV format.", etape2: "Check that it covers the WHOLE period since the account was opened: the rebuild starts from scratch at each import.", etape3: "Drop the file on this tile.", colonnes: "The file must have the columns datetime, date, category, type, asset_class, symbol, shares, price, amount and fee. The format is recognized automatically — no column mapping needed." },
  ledger: { sousTitre: "Crypto wallet", intro: "An export of your hardware wallet’s operations. Each receipt is treated as a purchase at the price on the day of receipt.", etape1: "Open Ledger Live on your computer.", etape2: "Request the export of the operations of all your accounts in CSV format.", etape3: "Drop the file on this tile, then untick unwanted tokens (spam, dust) before confirming.", colonnes: "The file must have the columns Operation Date, Status, Currency Ticker, Operation Type, Operation Amount and Countervalue at Operation Date." },
  bricks: { sousTitre: "Real estate crowdfunding", intro: "An export of your transactions: brick purchases, repayments and income received. The income feeds the dividend calendar.", etape1: "Log in to your Bricks.co space.", etape2: "Request the export of your transaction history (CSV or Excel).", etape3: "Drop the file on this tile.", colonnes: "The file must have the columns id, date, type, statut, propriété, type de contrat, montant (€) and prix de la brick (€). Only rows with status “Validée” are imported." },
  releve: { nom: "Positions statement", sousTitre: "Any other broker", intro: "For a broker whose format is not recognized automatically (Boursorama, Degiro, Interactive Brokers...). You map the file’s columns to the expected fields yourself.", etape1: "Export your portfolio from your broker in CSV or Excel format.", etape2: "Drop the file on this tile.", etape3: "Map at least a Ticker column and a Quantity column; cost basis, name, account and currency remain optional.", colonnes: "No column name required: the file is read as is and the mapping is done in the next step. The separator (comma, semicolon, tab) is detected automatically." },
  bancaire: { nom: "Bank transactions", sousTitre: "For the Budget screen", intro: "Your current account statement, which feeds the Budget screen — independent of the stock portfolio.", etape1: "From your online banking, export the account transactions in OFX, QIF or CSV format.", etape2: "Drop the file on this tile.", etape3: "An OFX or QIF is imported directly. A CSV requires mapping at least a Date column, a Description column and the amount column(s)." },
}

export default guidesExport
