import type fr from '../fr/partagePublicPage'
import type { Structure } from '../../types'

/** Anglais — espace « partagePublicPage » (backlog § BL.2), traduit depuis le français. */
const partagePublicPage: Structure<typeof fr> = {
  patrimoinePartage: "Shared wealth",
  consultation: "View",
  codeDAccesRequis: "Access code required",
  code: "Code",
  verification: "Checking...",
  acceder: "Access",
  aucuneDonnee: "No data.",
  patrimoineNet: "Net worth",
  actifsTotaux: "Total assets",
  passifs: "Liabilities",
  expositionConsolidee: "Consolidated exposure",
  plusGrosseLigne: "Largest holding",
  top5Lignes: "Top 5 holdings",
  premiereZone: "Top region",
  geographique: "Geographic",
  parClasseDActif: "By asset class",
  rentabilite: "Returns",
  gainPerteTotal: "Total gain/loss",
  rendementSimple: "Simple return",
  rendementAnnualise: "Annualized return",
  entrees: "Inflows",
  sorties: "Outflows",
  disponible: "Available",
  vueEnLectureSeuleGeneree: "Read-only view, generated by Lumen.",
  budgetPeriode: "Budget ({debut} to {fin})",
}

export default partagePublicPage
